version: '3.8'

services:
  minio:
    image: minio/minio
    ports:
      - 9000:9000
      - 9090:9090
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-admin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-password}
    command: server /data --console-address ":9090"
    networks:
      - mmvib-net

volumes:
  minio-data:

networks:
  mmvib-net:
    driver: bridge
    external: true
    name: mmvib-net
    
